### ISSUE TITLE
add-on does not support ingress

### ISSUE THREAD

**Issue by greymatter** [casperklein/homeassistant-addons#1]
I have installed the add on and it is indeed functioning but when I tried to link this through a custom_panel entry I received an error stating the add on does not support ingress.

are there plans to support ingress in the future?

thanks!

**Comment by casperklein** [comment]
I guess you are talking about the Netbox add-on? Unfortunately there is no easy way to implement ingress right now. I'll keep it in mind, but don't expect it to implemented soon.

If [panel iframe](https://www.home-assistant.io/integrations/panel_iframe/) would be an option for you, I could easily tweak the add-on to support this.

**Comment by greymatter** [comment]
Hi Casper, yes I am talking about NetBox, apologies for not being clear on that.  Also given the fact you put this together to share to the world for free, i have absolutely zero expectations, just gratitude and possibly a couple requests.

An panel iframe would be perfect for me so long as it would accessible through SSL.  that being said I do already have an addon running for postgres and PGAdmin on hassio so I can handle other PGSQL db's accross my network.  Would there be a way to expose 5432 in the netbox docker so that my PGAdmin instance could hit it and manage backups for that instance as well?

thanks Casper!

**Comment by casperklein** [comment]
I've created a test version you can try. Add [this](https://github.com/casperklein/homeassistant-addons-dev) repository to HA and install the `netbox-dev` addon.

>An panel iframe would be perfect for me so long as it would accessible through SSL

Currently Netbox is only available via HTTP. If you are accessing HA via HTTPS, you cannot use an iframe pointing to a HTTP site (afaik). But you can try it.

> Would there be a way to expose 5432 in the netbox docker

You can now expose the postgre port in the configuration tab of the addon (disabled by default).

Accessing the netbox database via CLI `psql -h 192.168.X.Y -p 5432 -U netbox` with password `netbox` worked in my test.

But keep in mind, that this is **not a secure setup**. The credentials cannot be changed. For your local trusted network that might be acceptable.

In case you wonder why some things in this addon are weak (no HTTPS support, hard-coded postgre credentials, etc.).. This was one of my first HA addons (and Docker images in general), which I hacked together mainly for teaching myself and get some experience. TBH, I don't even use it myself. That's why I only change/add things which are easy to implement.

**Comment by greymatter** [comment]
Hi Casper, man thanks for the fast response and hook up!  yeah I got it
installed and that does give me the ability to hit the postgres instance
with PGAdmin and even without fully exposing the port in the config page so
that's perfectly acceptable given not being able to change db pass for
netbox.  but as you said without ssl or ingres I don't think I can hit it
through an iframe given I am coming through HAProxy via SSL.

Thanks again Casper!!

-Todd

**Comment by casperklein** [comment]
Good to hear it's working. I've an idea how to easily implement HTTPS. I will look into it the next days.

**Comment by greymatter** [comment]
nice!  yeah i was finally able to restore my db and got a good test run!  i
had to reset postgres pass in order to get to backup to restore but that
was easy enough!

and again thanks a ton for helping me out!  i truly appreciate it!

Todd

**Comment by casperklein** [comment]
I've added HTTPS support. See version 2.10.4.2 from the dev-repo. Please report back if it works. Then I'll merge these changes into the stable addon.

**Comment by greymatter** [comment]
ran the update originally, it installed, but wouldn't start when I
originally tried, had https set to true and pointed at my certs, so i
removed the docker completely and retested with the same results, I tried
setting https to false to see if that made any difference but still no go.
I am getting only this in the logs while it attempts to start.  but that's
it.

Starting redis-server: redis-server.
Removed stale pid file.
Netbox: Creating new superuser: greymatter

**Comment by greymatter** [comment]
ok played around a bit, rebooted host and reinstalled and everything is
running fine.  ssl looks good first glance so i’ll play around with it let
you know if i see anything!  thx!

**Comment by casperklein** [comment]
I have to admit, that I found some issues myself and fixed them (after posting here). I guess you tried it with the buggy image at first. Sorry for that.

**Comment by casperklein** [comment]
I've merged the changes to the stable add-on. I would advice you, not to use the dev repo further, as this is my playground and things are expected to break occasionally.

**Comment by greymatter** [comment]
understood.  yeah reinstalled from your prod tepo this morning and it’s
running like a champ! thanks again for all this!

**Comment by casperklein** [comment]
Glad to hear that. 😃
