### ISSUE TITLE
webpage doesnt load on start

### ISSUE THREAD

**Issue by DellBoy4** [casperklein/homeassistant-addons#23]
I cant get the addon to load. it never loads a webpage. am i missing something?

**Comment by casperklein** [comment]
Please open a new issue (Bug report, not blank issue) and provide as much information as possible.

This issue is lacking essential information that are required to solve your problem:

- What Addon you are using
- What exactly did you do
- What is the expected behavior
- Things you may have tried
- Addon logs
- etc.
